# Generated by Django 5.2 on 2025-07-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_release_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(help_text='Short description of what the patch notes might contain'),
        ),
    ]
