# Generated by Django 5.2 on 2025-07-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_release_showcase_picture_url_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='showcase_picture_url_credits',
            new_name='showcase_picture_credits',
        ),
    ]
