# Generated by Django 5.2 on 2025-05-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='slug',
            field=models.CharField(default='testslug', max_length=60),
            preserve_default=False,
        ),
    ]
