# Generated by Django 5.2 on 2025-06-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_subtopic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='parent_subtopic',
        ),
    ]
