# Generated by Django 5.2 on 2025-06-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_profile_picture_user_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dcc',
        ),
    ]
