# Generated by Django 5.2 on 2025-07-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VFXProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VFXSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imgsrc', models.URLField(blank=True, max_length=1024, null=True)),
                ('actualimage', models.URLField(blank=True, max_length=1024, null=True)),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
                ('animation_supervisors', models.ManyToManyField(blank=True, related_name='movies', to='vfx.animationsupervisor')),
                ('directors', models.ManyToManyField(blank=True, related_name='movies', to='vfx.director')),
                ('producers', models.ManyToManyField(blank=True, related_name='movies', to='vfx.producer')),
                ('vfx_producers', models.ManyToManyField(blank=True, related_name='movies', to='vfx.vfxproducer')),
                ('vfx_supervisors', models.ManyToManyField(blank=True, related_name='movies', to='vfx.vfxsupervisor')),
            ],
        ),
    ]
