name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - "feature/terraform"
      

jobs:
  docker-build-and-push:
    runs-on: 'ubuntu-latest'
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        run: |
            docker build . -t  ${{ secrets. DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:${{github.sha}}
            docker push ${{ secrets. DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:${{github.sha}}

  deploy-cloud-run:
    runs-on: 'ubuntu-latest'
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4
    
      - name: 'Auth into GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_RFX_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER_ID}}

      - name: 'Write env vars file'
        run: |
          cat > env-vars.yaml << EOF
          

          EOF
          

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{secrets.GCP_CLOUD_RUN_SERVICE}}
          image: docker.io/${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:${{github.sha}}
          env_vars_file: 'env-vars.yaml'