name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - "main"
      

jobs:
  docker-build-and-push:
    runs-on: 'ubuntu-latest'
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        run: |
            docker build . -t  ${{ secrets. DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:${{github.sha}}
            docker push ${{ secrets. DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:${{github.sha}}

 
      - name: 'Auth into GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_RFX_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER_ID}}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{secrets.GCP_CLOUD_RUN_SERVICE}}
          image: docker.io/${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:${{github.sha}}
          env_vars: |-
            DB_NAME= ${{secrets.DB_NAME}}
            DB_USER=${{secrets.DB_USER}}
            DB_PASSWORD=${{secrets.DB_PASSWORD}}
            DB_HOST=${{secrets.DB_HOST}}
            DB_PORT=${{secrets.DB_PORT}}

            PRODUCTION=True

            DJANGO_SECRET_KEY=${{secrets.DJANGO_SECRET_KEY}}

            ALLOWED_HOSTS=${{secrets.ALLOWED_HOSTS}}
            CORS_ALLOWED_ORIGINS=${{secrets.CORS_ALLOWED_ORIGINS}}